### ISSUE TITLE
Create abstraction around `JobExecutionContext` to hide some implemenation details

### ISSUE THREAD

**Issue by linkdotnet** [NCronJob-Dev/NCronJob#59]
In #53 by @falvarez1 the `JobExecutionContext` has some internal details we don't want to expose. That includes the whole construction of the object itself.

To keep the current contract stable and let users be able to test their code, we had to add a ctor that mimics the old behavior.
That isn't a very nice way. The much cleaner approach is to create a `IJobExecutionContext` interface with the public stuff and make `JobExecutionContext` internal.

## ToDo
- [ ] Create `IJobExecutionContext` interface with the necessary stuff and make `JobExecutionContext` internal
- [ ] Update the docs
- [ ] Create an entry for a migration

**Comment by linkdotnet** [comment]
Done on `v3`
